version: '3.8'

services:
  react:
    image: node:18.18.0-alpine3.17
    container_name: react_service
    user: node
    working_dir: /home/node/app
    tty: true
    stdin_open: true
    ports:
      - 3000:5173
    volumes:
      - ./front:/home/node/app